BoardConfig: Get rid of Manifest SKUS
There's no point for having specific SKUs while we are using some inherited tree which already has additional device manifests
so we standarize naming for Manifest Files and allowing build system to apend inherited device_matrix or device_manifest files

Fixing this error while inheriting hardware_dolby from lunaris aosp :

stderr: [WARN] Cannot filter framework manifest HALs properly because target FCM version is unspecified in the device manifest. Treating as infinitely old device.
ERROR: Invalid argument: Device manifest does not specify Shipping FCM Version.